return {
	-- "folke/sidekick.nvim",
	-- opts = {
	-- 	-- add any options here
	-- 	cli = {
	-- 		mux = {
	-- 			backend = "tmux",
	-- 			enabled = false,
	-- 		},
	-- 	},
	-- },
	-- keys = {
	-- 	{
	-- 		"<tab>",
	-- 		function()
	-- 			-- if you are using Neovim's native inline completions
	-- 			if vim.lsp.inline_completion.get() then
	-- 				print("i got here and am doing a completion lol")
	-- 				return
	-- 			end
	--
	-- 			-- fall back to normal tab
	-- 			print("i got here")
	-- 			return "<tab>"
	-- 		end,
	-- 		mode = { "i", "n" },
	-- 		expr = true,
	-- 		desc = "Goto/Apply Next Edit Suggestion",
	-- 	},
	-- 	{
	-- 		"<c-.>",
	-- 		function()
	-- 			require("sidekick.cli").focus()
	-- 		end,
	-- 		mode = { "n", "x", "i", "t" },
	-- 		desc = "Sidekick Switch Focus",
	-- 	},
	-- 	{
	-- 		"<leader>aa",
	-- 		function()
	-- 			require("sidekick.cli").toggle({ focus = true })
	-- 		end,
	-- 		desc = "Sidekick Toggle CLI",
	-- 		mode = { "n", "v" },
	-- 	},
	-- 	{
	-- 		"<leader>ac",
	-- 		function()
	-- 			require("sidekick.cli").toggle({ name = "claude", focus = true })
	-- 		end,
	-- 		desc = "Sidekick Claude Toggle",
	-- 		mode = { "n", "v" },
	-- 	},
	-- 	{
	-- 		"<leader>ag",
	-- 		function()
	-- 			require("sidekick.cli").toggle({ name = "grok", focus = true })
	-- 		end,
	-- 		desc = "Sidekick Grok Toggle",
	-- 		mode = { "n", "v" },
	-- 	},
	-- 	{
	-- 		"<leader>ap",
	-- 		function()
	-- 			require("sidekick.cli").select_prompt()
	-- 		end,
	-- 		desc = "Sidekick Ask Prompt",
	-- 		mode = { "n", "v" },
	-- 	},
	-- },
}
